### PR TITLE
Add rudimentary GKE support

### PR DESCRIPTION
**Pull request by afirth**
I was using this for something else and thought I'd push the kubernetes deployment back up. Thanks for the example!

### CODE REVIEW

**Comment by afirth** [comment]
@menski @saig0 how are we dealing with this?

**Comment by saig0** [comment]
Hi @afirth, I'm sorry for the late response :see_no_evil: Thank you for contributing!

I'm not sure if the changes fit the purpose of this repository. It's coupled to the [Java Get-Started guide](https://docs.zeebe.io/java-client/get-started). I don't think that users want to deploy this code to Kubernetes following the guide. Maybe, we should move it somewhere else?

**Comment by afirth** [comment]
I wanted to use it on kube, that's why I wrote this :D Of course we could put it somewhere else later, but where would that be now?

**Comment by saig0** [comment]
As far as I understand, it is a template to deploy your Zeebe worker/application into GKE. I think it would be nice to create a new repository and mark it as a `template` repository.

**Comment by afirth** [comment]
closing since nobody wants to own this :)

**Pull request closed without merging**
